name: npm run workflow_dispatch
on: workflow_dispatch
jobs: 
  Build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Print hello
        run: echo "Hello world"

      - name: checkout the code
        uses: actions/checkout@v6

      - run: ls
