name: npm run workflow_dispatch
on: 
  pull_request: 
    types: 
      - opened
      - edited
    branches: 
      - master
  workflow_dispatch: 
    inputs: 
      Test: 
        type: string
        default: "Main"
  push: 
    branches: 
      - master
   
 

jobs: 
  Build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Print hello
        run: |
          echo "My name is ${{inputs.Test}}"

      - name: checkout the code
        uses: actions/checkout@v6

      - name: install node
        uses: actions/setup-node@v6
        with: 
          node-version: 18.*
      - name: install dependencies 
        run: |
          npm ci
          npm run build
          ls 
      - name: Testing...
        run: npm test

      - name: uploading the artifacts
        uses: actions/upload-artifact@v4
        with: 
          path: dist
          name: dist-files


  Deploy: 
    needs: Build 
    runs-on: ubuntu-latest
    steps: 
    - name: install node
      uses: actions/setup-node@v6 
      with: 
       node-version: 18.*
    - name: download artifacts
      uses: actions/download-artifact@v6
      with: 
        name: dist-files
    - run: ls
      


        
    

    

