name: npm run workflow_dispatch
on: workflow_dispatch
jobs: 
  Build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Print hello
        run: echo "Hello world"

      - name: checkout the code
        uses: actions/checkout@v6

      - name: install node
        uses: actions/setup-node@v6
        with: 
          node-version: 18.*
      - run: npm ci
      - run: npm test

  Deploy: 
    needs: Build 
    runs-on: ubuntu-latest
    steps: 
    - name: install node
      uses: actions/setup-node@v6 
      with: 
       node-version: 18.*
    - name: Fetch code
      uses: actions/checkout@v6 
    - name: install dependencies 
      run: |
        npm ci
        npm run build
        ls 

    

