name: npm run workflow_dispatch
on: 
  pull_request: 
    types: 
      - opened
      - edited
    branches: 
      - master
  workflow_dispatch: 
    inputs: 
      Test: 
        type: string
        default: "Main"
      env: 
        type: string
        default: "Dev"
  push: 
    branches: 
      - master
   
env: 
  name: coming from workflow

jobs: 
  Build: 
    env: 
      name: coming from jobs
    runs-on: ubuntu-latest 
    environment: DEV
    outputs: 
      NAME: ${{ steps.name.outputs.NAME }}
    steps: 
      - name: Print hello
        id: name
        run: |
          echo "My name is ${{inputs.Test}}"
          echo "NAME=pradeep" >> $GITHUB_OUTPUT
          echo "Env is ${{vars.name}}"
          printenv

      - name: checkout the code
        uses: actions/checkout@v6

      - name: install node
        uses: actions/setup-node@v6
        with: 
          node-version: 18.*
      - name: caching dependencies
        uses: actions/cache@v5
        with: 
          path: ~/.npm
          key: deps-${{hashFiles('**/package-lock.json')}}
      - name: install dependencies 
        run: |
          npm ci
          ls 
      - name: Testing...
        run: npm test

      - name: Building code
        run: npm run build

      - name: uploading the artifacts
        uses: actions/upload-artifact@v4
        with: 
          path: dist
          name: dist-files

  Test: 
    runs-on: ubuntu-latest
    needs: Build
    steps: 
      - name: Get code
        uses: actions/checkout@v6

      - name: install node
        uses: actions/setup-node@v6
        with: 
          node-version: 18.*

      - name: caching dependencies
        uses: actions/cache@v5
        with: 
          path: ~/.npm
          key: deps-${{hashFiles('**/package-lock.json')}}

      - name: install dependencies
        run: |
          npm ci
          npm run build

      - name: Test
        run: npm test


  Deploy: 
    needs: Build 
    runs-on: ubuntu-latest
    steps: 
    - name: displaying job output
      run: echo ${{ needs.Build.outputs.NAME }}
    - name: install node
      uses: actions/setup-node@v6 
      with: 
       node-version: 18.*
    - name: download artifacts
      uses: actions/download-artifact@v6
      with: 
        name: dist-files
    - run: ls
    - name: Deploy to ${{inputs.env}}
      run: echo Deployed to ${{inputs.env}} successfully
      


        
    

    

