name: use reusable workflow
on: [workflow_dispatch, push]

jobs: 
  Build: 
    uses: ./.github/workflows/reusable-workflow.yaml
    with: 
      env: "prod"
    secrets: 
      pat_token: ${{secrets.NAME}}
  Deploy:
    runs-on: ubuntu-latest
    container:
      image: mongo:6.0
    services:
      mongo:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017
    needs: Build
    steps:
      - name: Diplaying output of Build
        run: echo "${{needs.Build.outputs.result}}"

      - name: Wait for Mongo port
        run: |
          for i in {1..30}; do
            nc -z mongo 27017 && echo "Mongo port open" && exit 0
            echo "Waiting for Mongo..."
            sleep 10
          done
          echo "Mongo did not become ready in time"
          exit 1

      - name: Connection test mongo
        run: |
          mongosh "mongodb://root:root@mongo:27017/admin" --eval "db.runCommand({ ping: 1 })"