name: use reusable workflow
on: workflow_dispatch

jobs: 
  Build: 
    uses: ./.github/workflows/reusable-workflow.yaml
    with: 
      env: "prod"
    secrets: 
      pat_token: ${{secrets.NAME}}
      
  Deploy:
    runs-on: ubuntu-latest
    container:
      image: mongo:6.0
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017
    needs: Build
    steps:
      - name: Diplaying output of Build
        run: echo "${{needs.Build.outputs.result}}"

      - name: Connection test mongo
        run: |
          mongosh "mongodb://root:root@mongo:27017/admin" --eval "db.runCommand({ ping: 1 })"