name: use reusable workflow
on: workflow_dispatch
jobs: 
  Build: 
    uses: ./.github/workflows/reusable-workflow.yaml
    with: 
      env: "prod"
    secrets: 
        pat_token: ${{secrets.NAME}}
  Deploy: 
    runs-on: ubuntu-latest
    needs: Build
    steps: 
      - name: Diplaying output of Build
        echo: "${{needs.Build.outputs.result}}"